//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLPA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ActionID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string ProductName { get; set; }
        public string AuditArea { get; set; }
        public string State { get; set; }
        public bool IsDel { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
