//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLPA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionPlan
    {
        public int PlanID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime StartPlanDate { get; set; }
        public System.DateTime EndPlanDate { get; set; }
        public string AuditType { get; set; }
        public bool IsComplete { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<int> BanCi { get; set; }
    }
}
