//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLPA.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AFMESEntities : DbContext
    {
        public AFMESEntities()
            : base("name=AFMESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EHS> EHS { get; set; }
        public virtual DbSet<LineMachineMap> LineMachineMap { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<MachineEHS> MachineEHS { get; set; }
        public virtual DbSet<ProductDept> ProductDept { get; set; }
        public virtual DbSet<ProductLine> ProductLine { get; set; }
        public virtual DbSet<Weather> Weather { get; set; }
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<AreaMachineMap> AreaMachineMap { get; set; }
        public virtual DbSet<EmpAuditArea> EmpAuditArea { get; set; }
        public virtual DbSet<ProblemLog> ProblemLog { get; set; }
        public virtual DbSet<ProblemPic> ProblemPic { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<PlanAreaMap> PlanAreaMap { get; set; }
        public virtual DbSet<WorkProcess> WorkProcess { get; set; }
        public virtual DbSet<LPAActionResult> LPAActionResult { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<AuditItem> AuditItem { get; set; }
        public virtual DbSet<ActionPlan> ActionPlan { get; set; }
        public virtual DbSet<Problem> Problem { get; set; }
    }
}
