//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLPA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineMachineMap
    {
        public int MachineID { get; set; }
        public int ProLineId { get; set; }
        public string PDCode { get; set; }
        public Nullable<int> SN { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual ProductLine ProductLine { get; set; }
    }
}
