//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLPA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.LineMachineMap = new HashSet<LineMachineMap>();
        }
    
        public int MachineID { get; set; }
        public int ProcID { get; set; }
        public Nullable<int> DownCodeID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public double Speed { get; set; }
        public string Status { get; set; }
        public string NowStatus { get; set; }
        public string Quality { get; set; }
        public string ProductType { get; set; }
        public string QualityWarning { get; set; }
        public string Remark { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual ICollection<LineMachineMap> LineMachineMap { get; set; }
    }
}
