//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLPA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public int ProbID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public int ProblemRegion { get; set; }
        public string ProblemType { get; set; }
        public Nullable<int> MachineID { get; set; }
        public int Responsible { get; set; }
        public string ProblemDesc { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string Measure { get; set; }
        public string State { get; set; }
        public int Progress { get; set; }
        public string Remark { get; set; }
        public bool IsDel { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public string ImproveAdvice { get; set; }
    }
}
