//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLPA.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDept
    {
        public ProductDept()
        {
            this.ProductLine = new HashSet<ProductLine>();
        }
    
        public string PDCode { get; set; }
        public string Name { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual ICollection<ProductLine> ProductLine { get; set; }
    }
}
