//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekerSoft.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public int DeptID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string EmpCode { get; set; }
        public string Gender { get; set; }
        public string Tel { get; set; }
        public Nullable<int> StationID { get; set; }
        public string MgrType { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public bool IsDel { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    }
}
